package com.mercotrace.retailer.domain;

import static com.mercotrace.retailer.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InventoryLotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAllPropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertInventoryLotAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryLotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAllUpdatablePropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertInventoryLotUpdatableFieldsEquals(expected, actual);
        assertInventoryLotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAutoGeneratedPropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotUpdatableFieldsEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot relevant properties")
            .satisfies(a -> assertThat(a.getQty()).as("check qty").isEqualTo(expected.getQty()))
            .satisfies(a -> assertThat(a.getRemaining()).as("check remaining").isEqualTo(expected.getRemaining()))
            .satisfies(a ->
                assertThat(a.getCostPrice()).as("check costPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCostPrice())
            )
            .satisfies(a ->
                assertThat(a.getSellPrice()).as("check sellPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSellPrice())
            )
            .satisfies(a -> assertThat(a.getPurchaseDate()).as("check purchaseDate").isEqualTo(expected.getPurchaseDate()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()))
            .satisfies(a -> assertThat(a.getInvoiceNo()).as("check invoiceNo").isEqualTo(expected.getInvoiceNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotUpdatableRelationshipsEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot relationships")
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getStore()).as("check store").isEqualTo(expected.getStore()));
    }
}
