package com.mercotrace.retailer.domain;

import static com.mercotrace.retailer.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaleLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleLineAllPropertiesEquals(SaleLine expected, SaleLine actual) {
        assertSaleLineAutoGeneratedPropertiesEquals(expected, actual);
        assertSaleLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleLineAllUpdatablePropertiesEquals(SaleLine expected, SaleLine actual) {
        assertSaleLineUpdatableFieldsEquals(expected, actual);
        assertSaleLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleLineAutoGeneratedPropertiesEquals(SaleLine expected, SaleLine actual) {
        assertThat(actual)
            .as("Verify SaleLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleLineUpdatableFieldsEquals(SaleLine expected, SaleLine actual) {
        assertThat(actual)
            .as("Verify SaleLine relevant properties")
            .satisfies(a -> assertThat(a.getQty()).as("check qty").isEqualTo(expected.getQty()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleLineUpdatableRelationshipsEquals(SaleLine expected, SaleLine actual) {
        assertThat(actual)
            .as("Verify SaleLine relationships")
            .satisfies(a -> assertThat(a.getSale()).as("check sale").isEqualTo(expected.getSale()))
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()));
    }
}
